### ISSUE TITLE
Housekeeping for v1.0

### ISSUE THREAD

**Issue by eho-tacc** [eho-tacc/episimlab#27]
Clean up repository for an official v1.0 release. This will involve:

- [ ] git tag HEAD
- [ ] Package
	- [ ] `partition` submodule, much of which is unused
	- [ ] `network` submodule, all of which is unused
	- [ ] `model` submodule
- [ ] Build
	- [ ] Makefile
	- [ ] Possible switch to poetry, if cythonize supports
		- This [SO post](https://stackoverflow.com/questions/63679315/how-to-use-cython-with-poetry) indicates that this is an undocumented feature
- [ ] Misc.
	- [ ] Check `TODO` and `DEBUG` tags
	- [ ] Ensure all tests passing
- [ ] git tag HEAD
- [ ] Kick off CI/CD if enabled

**Comment by eho-tacc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up Episimlab repo](https://trello.com/c/2cVmMPC5/16-clean-up-episimlab-repo)

**Comment by eho-tacc** [comment]
### TODO Tags

- [ ] [NaN checks](https://github.com/eho-tacc/episimlab/blob/2e34d96ba2f61ba69580cdb10fe279af361eb47e/tests/test_seir/test_bf_cython_seir.py#L29)
