### ISSUE TITLE
New SEIR process with FOI included

### ISSUE THREAD

**Issue by eho-tacc** [eho-tacc/episimlab#33]
Addition of vaccination compartment depends on two separate FOIs with different beta values for vaccinated and unvaccinated individuals. The easiest way to implement this as of now is to call the Cython function `_brute_force_FOI` twice within a new Cython function similar to `_brute_force_SEIR`.

## Work Plan

Work on this issue will be test driven.
- [x] New branch
- [x] New PR
- [x] Failing import pytest
- [x] New `xs.process`
- [x] Failing pytest for import of new `models.basic` model `seir_with_foi`
- [x] New model `seir_with_foi`
- [x] New pytest to include `models.basic.seir_with_foi` in `TestToyModels.test_sanity`
- [x] Failing pytest for `models.basic.seir_with_foi` in `TestCompareBasicModels`
- [x] New Cython function `episimlab.seir.bf_cython_engine.seir_with_foi`

**Comment by eho-tacc** [comment]
Instead of including model as parameter in `TestCompareBasicModels`, I wrote a new pytest `test_consistent_with_foi_separate`.
